import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="nav-bar">
          <div className="logoDiv">
            <Image src="/logo2.png"
              width={150}
              height={150}
              className="logo-nav"
              alt="Logo Moj Kutak"
            />
          </div>
          <div className="nav-links">
            <Link href="/" className="nav-item">Home</Link>
            <Link href="/katalog" className="nav-item">Katalog</Link>
            <Link href="/kontakt" className="nav-item">Kontakt</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
